# Generated by Django 5.2.6 on 2026-03-03 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajadores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcluidoCumpleanos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Correo electrónico de la cuenta a excluir', max_length=254, unique=True)),
                ('vigente', models.BooleanField(default=True, help_text='Indica si la exclusión está activa')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='trabajador',
            name='foto',
        ),
    ]
